---
- name: run show cmd
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: "network_cli"
    ansible_network_os: "ios"
    ansible_user: "cisco"
    ansible_password: "cisco"
  tasks:
    - name: run sh ver
      ios_command:
        commands: show version
      register: cli_result
    - name: print result
      debug:
        msg: "{{ cli_result.stdout_lines[0] }}"
